[package]
name = "xirr_uda"
version = "0.1.0"
edition = "2021"

[dependencies]
datafusion = "38.0.0"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
chrono = "0.4.31"
async-trait = "0.1.80"
xirr = "0.3.2"
jiff = "0.2.18"